#define WP_CONNECT_SUCCESS                @"WP_Connect_Success"
#define WP_CONNECT_FAILED                 @"WP_Connect_Failed"

#define WP_UPDATE_POINTS                  @"WP_UPDATE_POINTS"
#define WP_GET_POINTS_SUCCESS             @"WP_GET_POINTS_SUCCESS"
#define WP_GET_POINTS_FAILED              @"WP_GET_POINTS_FAILED"
#define WP_SPEND_POINTS_SUCCESS           @"WP_SPEND_POINTS_SUCCESS"
#define WP_SPEND_POINTS_FAILED            @"WP_SPEND_POINTS_FAILED"
#define WP_AWARD_POINTS_SUCCESS           @"WP_AWARD_POINTS_SUCCESS"
#define WP_AWARD_POINTS_FAILED            @"WP_AWARD_POINTS_FAILED"
#define WP_POINTS_EARNED                  @"WP_POINTS_EARNED"

#define WP_LIST_CLOSED                   @"WP_LIST_CLOSED"

#define WP_BANNERAD_SHOW                  @"WP_BANNER_SHOW"
#define WP_BANNERAD_CLICK                 @"WP_BANNER_CLICK"
#define WP_BANNERAD_FAILED                @"WP_BANNER_FAILED"
#define WP_BANNERAD_CLOSED                @"WP_BANNER_CLOSED"

#define WP_POPAD_INIT_SUCESS              @"WP_POP_INIT_SUCESS"
#define WP_POPAD_INIT_NULL                @"WP_POP_INIT_NULL"
#define WP_POPAD_INIT_FAILED              @"WP_POP_INIT_FAILED"
#define WP_POPAD_SHOW_SUCESS              @"WP_POP_SHOW_SUCESS"
#define WP_POPAD_SHOW_FAILED              @"WP_POP_SHOW_FAILED"
#define WP_POPAD_CLOSED                   @"WP_POP_CLOSED"
#define WP_POPAD_CLICKED                  @"WP_POP_CLICKED"
#define WP_MENU_SHOW                      @"WP_MENU_SHOW"

#define WP_PUSH_UPLOADDEVICE_SUCCESS      @"WP_PUSH_UPLOADDEVICE_SUCCESS"
#define WP_PUSH_UPLOADDEVICE_FAILED       @"WP_PUSH_UPLOADDEVICE_FAILED"

#define AD_SIZE_320X50        @"320x50"
#define AD_SIZE_375x65        @"375x60"
#define AD_SIZE_414x70        @"414x70"
#define AD_SIZE_480X75        @"480X75"
#define AD_SIZE_640X100       @"640x100"
#define AD_SIZE_768X90        @"768x90"
#define AD_SIZE_768X100       @"768x100"

#import "WPLog.h"
#import "WPAdViewHandler.h"
#import "WPUserPoints.h"
#import "WPPointsManager.h"
#import "WPCallsWrapper.h"
#import "WPTBXML.h"
#import "WPListViewHandler.h"
#import "WPPopViewHandler.h"
#import "WPRemotePush.h"